name: Typerighter CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "corretto"
      - name: Build the stack
        run: | 
          docker-compose up -d
      - name: Run tests
        run: |
          sbt -v test
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build rule-manager-client
        working-directory: ./apps/rule-manager/client
        run: |
          npm i
          npm run build
      - name: build rule-audit-client
        working-directory: ./apps/rule-audit-client
        run: |
          npm i
          npm run build
      - name: cdk synth
        working-directory: ./cdk
        run: |
          yarn
          yarn synth
      - name: build sbt
        run: |
          sbt clean compile test riffRaffUpload
  
